name: Deploy to Azure Web App

on:
  push:
    branches: 
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Upload artifacts for deployment
      #   run: zip -r site.zip *

      - name: Install dependencies
        run: npm install --production

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: html-demo-pipeline
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
